# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Winter is coming
email: XunMengWinter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just remember in the winter
  Far beneath the bitter snow
  Lies the seed that with the sun's love
  In the spring becomes the rose

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wefor.top" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  XunMengWinter

# Build settings
markdown: kramdown
